name: GH Releases Mirror
on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install deps
        run: sudo apt-get install wget -y
      
      - name: Download
        run: wget https://bigota.d.miui.com/V12.5.7.0.RJDEUXM/miui_APOLLOEEAGlobal_V12.5.7.0.RJDEUXM_5900218774_11.0.zip 

      - name: Post a Github Release
        run: hub release create -a *.zip -m 'ROM Build' $(date +%s)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
