name: GH Releases Mirror
on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install deps
        run: sudo apt-get install wget -y
      
      - name: Download
        run: wget https://sourceforge.net/projects/ashwin-rom-builds/files/mojito/Project_Radiant/ProjectRadiant-1.1-VANILLA-mojito-20211007-1227-UNOFFICIAL.zip

      - name: Post a Github Release
        run: hub release create -a *.zip -m 'ROM Build' $(date +%s)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
